package emitter

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/geo-suite/geovisor/internal/tir"
)

// WebMCPAPIVersion identifies the browser API used by generated modules.
const WebMCPAPIVersion = "Chrome 153 imperative API, updated 2026-09-01"

// WebMCP emits an ES module that registers executable browser-local tools.
type WebMCP struct{}

func (WebMCP) Format() Format {
	return FormatWebMCP
}

type webMCPDefinition struct {
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	InputSchema *jsonSchema            `json:"inputSchema"`
	Annotations webMCPAnnotations      `json:"annotations"`
	Actions     []tir.ActionBinding    `json:"actions"`
	Locators    []tir.LocatorCandidate `json:"locators"`
}

type webMCPAnnotations struct {
	ReadOnlyHint         bool `json:"readOnlyHint"`
	ConsequentialHint    bool `json:"consequentialHint"`
	UntrustedContentHint bool `json:"untrustedContentHint"`
}

func (WebMCP) Emit(
	ctx context.Context,
	document *tir.Document,
	_ Options,
) (Result, error) {
	canonical, err := canonicalDocument(ctx, FormatWebMCP, document)
	if err != nil {
		return Result{}, err
	}
	definitions := make([]webMCPDefinition, 0, len(canonical.Tools))
	for ti := range canonical.Tools {
		if err := canceled(ctx, FormatWebMCP); err != nil {
			return Result{}, err
		}
		tool := &canonical.Tools[ti]
		for ai, action := range tool.Actions {
			if len(action.LocatorCandidateIDs) == 0 {
				return Result{}, failure(
					FormatWebMCP,
					CodeUnsupportedShape,
					fmt.Sprintf("tools[%q].actions[%d].locatorCandidateIds", tool.ID, ai),
					"executable WebMCP actions require at least one locator candidate",
				)
			}
		}
		inputSchema, err := toolInputSchema(ctx, FormatWebMCP, tool, false)
		if err != nil {
			return Result{}, err
		}
		definitions = append(definitions, webMCPDefinition{
			Name:        tool.ID,
			Description: tool.Description,
			InputSchema: inputSchema,
			Annotations: deriveWebMCPAnnotations(tool.Actions),
			Actions:     tool.Actions,
			Locators:    tool.Locators,
		})
	}
	definitionsJSON, err := json.Marshal(definitions)
	if err != nil {
		return Result{}, wrap(FormatWebMCP, CodeMarshal, "", err)
	}
	data := make([]byte, 0, len(definitionsJSON)+len(webMCPRuntime))
	data = append(data, webMCPPrefix...)
	data = append(data, definitionsJSON...)
	data = append(data, webMCPRuntime...)
	return Result{Primary: Artifact{
		Name:      "tools.webmcp.js",
		MediaType: "text/javascript",
		Data:      data,
	}}, nil
}

func deriveWebMCPAnnotations(actions []tir.ActionBinding) webMCPAnnotations {
	readOnly := true
	consequential := false
	for _, action := range actions {
		if action.SideEffect.Class != tir.SideEffectNone {
			readOnly = false
		}
		switch action.SideEffect.Class {
		case tir.SideEffectNetwork, tir.SideEffectNavigation,
			tir.SideEffectSubmission, tir.SideEffectUnknown:
			consequential = true
		}
	}
	return webMCPAnnotations{
		ReadOnlyHint:         readOnly,
		ConsequentialHint:    consequential,
		UntrustedContentHint: false,
	}
}

const webMCPPrefix = `// Generated by GEO-Visor for the Chrome 153 WebMCP imperative API.
if (typeof document === "undefined" ||
    !document.modelContext ||
    typeof document.modelContext.registerTool !== "function") {
  throw new Error("GEO-Visor WebMCP requires document.modelContext.registerTool (Chrome 153 or compatible).");
}

const __geovisorDefinitions = `

const webMCPRuntime = `;

function __geovisorElements(root) {
  if (!root || typeof root.querySelectorAll !== "function") {
    throw new Error("locator root does not support DOM queries");
  }
  return Array.from(root.querySelectorAll("*"));
}

function __geovisorRole(element) {
  const explicit = element.getAttribute("role");
  if (explicit) return explicit;
  const tag = element.localName;
  if (tag === "button") return "button";
  if (tag === "select") return element.multiple ? "listbox" : "combobox";
  if (tag === "textarea") return "textbox";
  if (tag === "a" && element.hasAttribute("href")) return "link";
  if (tag === "img") return "img";
  if (tag === "iframe" || tag === "frame") return "iframe";
  if (tag === "form") return "form";
  if (tag === "input") {
    const type = (element.getAttribute("type") || "text").toLowerCase();
    if (type === "checkbox") return "checkbox";
    if (type === "radio") return "radio";
    if (type === "button" || type === "submit" || type === "reset") return "button";
    if (type === "range") return "slider";
    if (type === "number") return "spinbutton";
    if (type !== "hidden") return type === "search" ? "searchbox" : "textbox";
  }
  return "";
}

function __geovisorName(element) {
  const labelledBy = element.getAttribute("aria-labelledby");
  if (labelledBy) {
    const documentRoot = element.ownerDocument;
    const text = labelledBy.split(/\s+/).map((id) => {
      const label = documentRoot.getElementById(id);
      return label ? label.textContent.trim() : "";
    }).filter(Boolean).join(" ");
    if (text) return text;
  }
  const ariaLabel = element.getAttribute("aria-label");
  if (ariaLabel !== null) return ariaLabel;
  if (element.labels && element.labels.length) {
    return Array.from(element.labels).map((label) => label.textContent.trim()).filter(Boolean).join(" ");
  }
  const alt = element.getAttribute("alt");
  if (alt !== null) return alt;
  const title = element.getAttribute("title");
  if (title !== null) return title;
  return (element.textContent || "").trim().replace(/\s+/g, " ");
}

function __geovisorSemantic(root, semantic) {
  let scope = root;
  for (const node of semantic.scope || []) {
    scope = __geovisorSemanticNode(scope, node);
  }
  return __geovisorSemanticNode(scope, semantic);
}

function __geovisorSemanticNode(root, node) {
  const matches = __geovisorElements(root).filter((element) => {
    if (__geovisorRole(element) !== node.role) return false;
    return !Object.prototype.hasOwnProperty.call(node, "name") ||
      __geovisorName(element) === node.name;
  });
  if (!matches.length) {
    const suffix = Object.prototype.hasOwnProperty.call(node, "name") ?
      " and name " + JSON.stringify(node.name) : "";
    throw new Error("no element with role " + JSON.stringify(node.role) + suffix);
  }
  return matches[0];
}

function __geovisorPathNode(root, node) {
  const failures = [];
  if (node.semantic) {
    try {
      return __geovisorSemanticNode(root, node.semantic);
    } catch (error) {
      failures.push("semantic: " + error.message);
    }
  }
  if (node.cssFallback) {
    try {
      const match = root.querySelector(node.cssFallback);
      if (match) return match;
      failures.push("CSS " + JSON.stringify(node.cssFallback) + " matched no element");
    } catch (error) {
      failures.push("CSS " + JSON.stringify(node.cssFallback) + " is invalid: " + error.message);
    }
  }
  throw new Error(failures.join("; ") || "path node has no locator strategy");
}

function __geovisorCandidate(candidate) {
  let root = document;
  for (let index = 0; index < candidate.framePath.length; index += 1) {
    const frame = __geovisorPathNode(root, candidate.framePath[index]);
    if (frame.localName !== "iframe" && frame.localName !== "frame") {
      throw new Error("framePath[" + index + "] resolved to <" + frame.localName + ">, not a frame");
    }
    let childDocument;
    try {
      childDocument = frame.contentDocument;
    } catch (error) {
      throw new Error("framePath[" + index + "] is cross-origin and inaccessible: " + error.message);
    }
    if (!childDocument) {
      throw new Error(
        "framePath[" + index + "] is cross-origin, unavailable, or not loaded; " +
        "page JavaScript cannot bypass this browser boundary"
      );
    }
    root = childDocument;
  }
  for (let index = 0; index < candidate.shadowPath.length; index += 1) {
    const host = __geovisorPathNode(root, candidate.shadowPath[index]);
    if (!host.shadowRoot) {
      throw new Error("shadowPath[" + index + "] resolved to a host without an open shadow root");
    }
    root = host.shadowRoot;
  }
  const failures = [];
  if (candidate.semantic) {
    try {
      return __geovisorSemantic(root, candidate.semantic);
    } catch (error) {
      failures.push("semantic: " + error.message);
    }
  }
  if (candidate.cssFallback) {
    try {
      const match = root.querySelector(candidate.cssFallback);
      if (match) return match;
      failures.push("CSS " + JSON.stringify(candidate.cssFallback) + " matched no element");
    } catch (error) {
      failures.push("CSS " + JSON.stringify(candidate.cssFallback) + " is invalid: " + error.message);
    }
  }
  throw new Error(failures.join("; ") || "candidate has no locator strategy");
}

function __geovisorResolve(definition, binding) {
  const failures = [];
  for (const locatorID of binding.locatorCandidateIds) {
    const candidate = definition.locators.find((item) => item.id === locatorID);
    if (!candidate) {
      failures.push(locatorID + ": locator definition is missing");
      continue;
    }
    try {
      return __geovisorCandidate(candidate);
    } catch (error) {
      failures.push(locatorID + ": " + error.message);
    }
  }
  throw new Error("all locator candidates failed (" + failures.join(" | ") + ")");
}

function __geovisorDispatch(element, name) {
  const EventConstructor = element.ownerDocument.defaultView.Event;
  element.dispatchEvent(new EventConstructor(name, { bubbles: true }));
}

function __geovisorApply(element, binding, value) {
  if (binding.action === "click") {
    if (typeof element.click !== "function") throw new Error("resolved element is not clickable");
    element.click();
    return;
  }
  if (binding.action === "fill") {
    if (!("value" in element) && !element.isContentEditable) {
      throw new Error("resolved element cannot accept text");
    }
    if (element.isContentEditable) element.textContent = String(value);
    else element.value = String(value);
    __geovisorDispatch(element, "input");
    __geovisorDispatch(element, "change");
    return;
  }
  if (binding.action === "select") {
    if (element.localName !== "select") throw new Error("resolved element is not a select");
    element.value = String(value);
    if (element.value !== String(value)) throw new Error("requested option does not exist");
    __geovisorDispatch(element, "input");
    __geovisorDispatch(element, "change");
    return;
  }
  if (binding.action === "check") {
    if (element.localName !== "input" ||
        !["checkbox", "radio"].includes((element.type || "").toLowerCase())) {
      throw new Error("resolved element is not a checkbox or radio input");
    }
    element.checked = binding.inputParameter ? Boolean(value) : true;
    __geovisorDispatch(element, "input");
    __geovisorDispatch(element, "change");
    return;
  }
  throw new Error("unsupported action " + JSON.stringify(binding.action));
}

async function __geovisorExecute(definition, input, signal) {
  if (signal && signal.aborted) throw new DOMException("Tool execution was canceled", "AbortError");
  for (let index = 0; index < definition.actions.length; index += 1) {
    if (signal && signal.aborted) throw new DOMException("Tool execution was canceled", "AbortError");
    const binding = definition.actions[index];
    if (binding.inputParameter &&
        !Object.prototype.hasOwnProperty.call(input, binding.inputParameter)) {
      continue;
    }
    try {
      const element = __geovisorResolve(definition, binding);
      const value = binding.inputParameter ? input[binding.inputParameter] : undefined;
      __geovisorApply(element, binding, value);
    } catch (error) {
      throw new Error(
        "GEO-Visor tool " + JSON.stringify(definition.name) + " action[" + index + "] " +
        JSON.stringify(binding.action) + " failed: " + error.message
      );
    }
  }
  return { content: [{ type: "text", text: "Executed " + definition.name }] };
}

export const geovisorRegistrations = [];
for (const definition of __geovisorDefinitions) {
  const registration = {
    name: definition.name,
    description: definition.description,
    inputSchema: definition.inputSchema,
    annotations: definition.annotations,
    execute: async (input, options = {}) =>
      __geovisorExecute(definition, input || {}, options.signal),
  };
  await document.modelContext.registerTool(registration);
  geovisorRegistrations.push(registration);
}
`
