package emitter

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"

	"github.com/wheelsmif/geovisor/internal/tir"
)

// webMCPRuntime is generated from client/src/webmcp-runtime.ts by the pinned
// esbuild toolchain, which is also what builds the extraction payload. Sharing
// one source tree is what keeps role resolution, accessible-name computation,
// and element addressing identical on the producer and consumer sides; when the
// runtime was a Go string literal it had silently drifted from the extractor
// (GV-001, GV-003, GV-004, GV-049).
//
//go:embed webmcp-runtime.js
var webMCPRuntime string

// WebMCPAPIVersion identifies the browser API used by generated modules.
const WebMCPAPIVersion = "Chrome 153 imperative API, updated 2026-09-01"

// WebMCP emits an ES module that registers executable browser-local tools.
type WebMCP struct{}

func (WebMCP) Format() Format {
	return FormatWebMCP
}

type webMCPDefinition struct {
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	InputSchema *jsonSchema            `json:"inputSchema"`
	Annotations webMCPAnnotations      `json:"annotations"`
	Actions     []tir.ActionBinding    `json:"actions"`
	Locators    []tir.LocatorCandidate `json:"locators"`
}

type webMCPAnnotations struct {
	ReadOnlyHint         bool `json:"readOnlyHint"`
	ConsequentialHint    bool `json:"consequentialHint"`
	UntrustedContentHint bool `json:"untrustedContentHint"`
}

func (WebMCP) Emit(
	ctx context.Context,
	document *tir.Document,
	options Options,
) (Result, error) {
	canonical, err := canonicalDocument(ctx, FormatWebMCP, document)
	if err != nil {
		return Result{}, err
	}
	definitions := make([]webMCPDefinition, 0, len(canonical.Tools))
	for ti := range canonical.Tools {
		if err := canceled(ctx, FormatWebMCP); err != nil {
			return Result{}, err
		}
		tool := &canonical.Tools[ti]
		for ai, action := range tool.Actions {
			if len(action.LocatorCandidateIDs) == 0 {
				return Result{}, failure(
					FormatWebMCP,
					CodeUnsupportedShape,
					fmt.Sprintf("tools[%q].actions[%d].locatorCandidateIds", tool.ID, ai),
					"executable WebMCP actions require at least one locator candidate",
				)
			}
		}
		inputSchema, err := toolInputSchema(ctx, FormatWebMCP, tool, options.Strict)
		if err != nil {
			return Result{}, err
		}
		definitions = append(definitions, webMCPDefinition{
			Name:        tool.ID,
			Description: tool.Description,
			InputSchema: inputSchema,
			Annotations: deriveWebMCPAnnotations(tool.Actions),
			Actions:     tool.Actions,
			Locators:    tool.Locators,
		})
	}
	definitionsJSON, err := json.Marshal(definitions)
	if err != nil {
		return Result{}, wrap(FormatWebMCP, CodeMarshal, "", err)
	}
	size := len(webMCPPrefix) + len(definitionsJSON) + len(webMCPDefinitionsEnd) +
		len(webMCPRuntime) + len(webMCPRegistration)
	data := make([]byte, 0, size)
	data = append(data, webMCPPrefix...)
	data = append(data, definitionsJSON...)
	data = append(data, webMCPDefinitionsEnd...)
	data = append(data, webMCPRuntime...)
	data = append(data, webMCPRegistration...)
	return Result{Primary: Artifact{
		Name:      "tools.webmcp.js",
		MediaType: "text/javascript",
		Data:      data,
	}}, nil
}

func deriveWebMCPAnnotations(actions []tir.ActionBinding) webMCPAnnotations {
	readOnly := true
	consequential := false
	for _, action := range actions {
		if action.SideEffect.Class != tir.SideEffectNone {
			readOnly = false
		}
		switch action.SideEffect.Class {
		case tir.SideEffectNetwork, tir.SideEffectNavigation,
			tir.SideEffectSubmission, tir.SideEffectUnknown:
			consequential = true
		}
	}
	return webMCPAnnotations{
		ReadOnlyHint:         readOnly,
		ConsequentialHint:    consequential,
		UntrustedContentHint: true,
	}
}

const webMCPPrefix = `// Generated by GEO-Visor for the Chrome 153 WebMCP imperative API.
if (typeof document === "undefined" ||
    !document.modelContext ||
    typeof document.modelContext.registerTool !== "function") {
  throw new Error("GEO-Visor WebMCP requires document.modelContext.registerTool (Chrome 153 or compatible).");
}

const __geovisorDefinitions = `

// webMCPDefinitionsEnd terminates the definitions statement before the embedded
// runtime bundle, which begins with its own "use strict" directive.
const webMCPDefinitionsEnd = ";\n\n"

const webMCPRegistration = `
export const geovisorRegistrations = await __geovisorRuntime.register(__geovisorDefinitions);
`
